---
- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == 'Debian'


- name: install deps
  apt: >
    pkg={{item}}
    state=installed
  with_items:
    - python-pip
    - python-dev
  when: ansible_os_family == 'Debian'

- name: install python module consulate
  pip: >
    name={{item}}
  with_items:
    - tornado
    - consulate
