---
- include: install.yml
- { include: install-ui.yml, when: consul_is_ui }
- { include: dnsmasq.yml, when: consul_install_dnsmasq }
- include: consulate.yml
- include: service.yml
- { include: wan.yml, when: consul_join_wan_addrs is defined }
