---
- name: restart consul
  action: service name=consul state=restarted

- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes

- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted
